name: Automate Data Retrieval and Sheet Updates

on:
  schedule:
    # Run on the 1st, 15th, and last day of each month
    - cron: "0 0 1,15 * *"
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update_sheet:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Adjust based on your version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Save service account credentials to a file
      - name: Set up Google API credentials
        run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_DATA }}" > googleapi.json

      # Debugging step to list files in the current directory
      - name: List files in current directory
        run: ls -la ${{ github.workspace }}

      # Step 5: Run the Python script with the correct working directory
      - name: Run Python script
        run: python python-code
        working-directory: ${{ github.workspace }}
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

      # Step 6: Clean up sensitive files (e.g., remove googleapi.json)
      - name: Clean up credentials
        run: rm googleapi.json
